In [5]:
import numpy as np

print(np)
print(np.__version__)

<module 'numpy' from '/opt/anaconda3/lib/python3.12/site-packages/numpy/__init__.py'>
1.26.4


In [11]:
a = np.arange(15).reshape(3, 5)
print(a)  # 利用 print(...) 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
print(a.dtype) # 每個元素都是 64 位元 (bits) 的整數
print(a.itemsize) # 8 byte = 64 bit (1 byte = 8 bit)

int64
8


In [21]:
print(a.dtype == 'int64')
print(a.dtype == np.int64)
print(a.dtype is np.dtype('int64'))

True
True
True
