In [1]:
import numpy as np

In [21]:
a = np.arange(15).reshape(3, 5)
print(a)
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
print(type(a))

<class 'numpy.ndarray'>


In [27]:
print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize) # 每個元素佔用的記憶體有幾個 byte
print('data: ', a.data)

ndim:  2
shape:  (3, 5)
size:  15
dtype:  int64
itemsize:  8
data:  <memory at 0x1074d8c70>


In [33]:
print('list(a): ', list(a))
print('tolist(a): ', a.tolist())

list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist(a):  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
