# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [20]:
import numpy as np

a = np.array([1, 2, 3]) # 一維陣列
b = np.array([[1, 2, 3], [4, 5, 6]]) # 二維陣列
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # 三維陣列

In [14]:
print(list(a))
print(a.tolist())

[1, 2, 3]
[1, 2, 3]


In [16]:
print(list(b))
print(b.tolist())

[array([1, 2, 3]), array([4, 5, 6])]
[[1, 2, 3], [4, 5, 6]]


In [24]:
print(list(c))
print(c.tolist())

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [32]:
# list(a): 只拆開最外層，裡面還是陣列 (array)
# a.tolist(a): 一層層徹底拆開，變成 nested list

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [34]:
import numpy as np

In [64]:

a = np.random.randint(10, size=6) 

print(a)
print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('length: ', len(a))
print('type: ', type(a))

[6 1 3 5 7 6]
ndim:  1
shape:  (6,)
size:  6
dtype:  int64
itemsize:  8
length:  6
type:  <class 'numpy.ndarray'>


In [80]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print('length: ', len(b))
print('type: ', type(b))

[[8 6 8 4]
 [5 2 8 5]
 [9 2 1 4]]
ndim:  2
shape:  (3, 4)
size:  12
dtype:  int64
itemsize:  8
length:  3
type:  <class 'numpy.ndarray'>


In [86]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print('length: ', len(c))
print('type: ', type(c))

# Compare the difference between "size (所有元素數量) " and "len (最外面那層) "

[[[2 5]
  [5 1]
  [6 0]]

 [[4 5]
  [4 6]
  [3 9]]]
ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int64
itemsize:  8
length:  2
type:  <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [90]:
def tolist(iterable):
    if type(iterable) != np.ndarray: # 非 array 的 else 會直接回傳原值
        return iterable
    newlist = []
    for obj in iterable: # 針對是 array 的值
        newlist.append(tolist(obj)) # 對每個元素 obj，再次調用 tolist 函數進行遞歸處理，這樣如果 obj 還是一個多維陣列，會進一步將它轉換為列表
    return(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 1, 3, 5, 7, 6]
[[8, 6, 8, 4], [5, 2, 8, 5], [9, 2, 1, 4]]
[[[2, 5], [5, 1], [6, 0]], [[4, 5], [4, 6], [3, 9]]]


In [102]:
b1 = b.tolist()
print(b1)
print(tolist(b1))

[[8, 6, 8, 4], [5, 2, 8, 5], [9, 2, 1, 4]]
[[8, 6, 8, 4], [5, 2, 8, 5], [9, 2, 1, 4]]
